services:

  Haskel\TelegramBundle\Routing\RouteLoader:
    tags:
      - { name: 'routing.loader', priority: 0 }

  Haskel\TelegramBundle\Serializer\UpdateDeserializer: ~

  Haskel\TelegramBundle\Routing\BotRouter:
    bind:
      $cacheFile: '%kernel.cache_dir%/haskel_bot.php'
      $logger: '@logger'

  Haskel\TelegramBundle\Routing\ScenarioResolver: ~

  Haskel\TelegramBundle\Storage\Adapter\FileQueue:
    arguments:
      - '%kernel.cache_dir%/queue.jsonl'
      - '@Haskel\TelegramBundle\Serializer\UpdateDeserializer'

  Haskel\TelegramBundle\Storage\UpdateQueue: '@Haskel\TelegramBundle\Storage\Adapter\FileQueue'

  Haskel\TelegramBundle\Listener\RequestListener:
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: -256 }
    arguments:
        - '@Haskel\TelegramBundle\Serializer\UpdateDeserializer'
        - '@Haskel\TelegramBundle\Routing\BotRouter'
        - '@Haskel\TelegramBundle\Routing\ScenarioResolver'
        - '@logger'
        - '@Haskel\TelegramBundle\Storage\UpdateQueue'

  Haskel\TelegramBundle\ArgumentResolver:
    tags:
      - { name: 'controller.argument_value_resolver', priority: 0 }

  Haskel\TelegramBundle\Listener\ViewListener:
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.view', method: 'onKernelView', priority: 0 }
    arguments:
      - '@Haskel\TelegramBundle\TelegramApiPool'

  Haskel\TelegramBundle\Listener\ExceptionListener:
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException', priority: 0 }
    arguments:
      - '@logger'